# Generated by Django 4.2.11 on 2024-03-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('max_participation', models.PositiveIntegerField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
